### ISSUE TITLE
Cedar 16

### ISSUE THREAD

**Issue by funkenstrahlen** [Xerpa/heroku-buildpack-graphicsmagick#1]
Does this work with Cedar 16 on heroku?

**Comment by nirev** [comment]
We have stopped using heroku for a while now, so I cannot say if it works with Heroku-16. We were using it in production with Cedar-14.

It's possible it will work, but might be missing some dependencies since they reduced the image size.
You can call compile inside a Heroku-16 docker image to try and see if it works. If it needs some addition to make it work, feel free to open a PR!

**Comment by tomsoderlund** [comment]
I had problems with Cedar-16, but got it to work fine after downgrading to Cedar-14.

**Comment by funkenstrahlen** [comment]
@tomsoderlund Maybe this will help you: https://github.com/mcollina/heroku-buildpack-graphicsmagick/issues/27
